### ISSUE TITLE
Cloud logging

### ISSUE THREAD

**Issue by SUDALV92** [yandex-cloud/dotnet-sdk#11]
Hi, when Cloud Logging is planned to be implemented?

**Comment by nikolaymatrosov** [comment]
It is implemented already.

**Comment by SUDALV92** [comment]
I get 

`System.Exception: 'service Services_Logging is not supported at this moment'`

when i'm trying to use `LogIngestionService.WriteAsync`

**Comment by nikolaymatrosov** [comment]
My bad. You are right. The service is missing in the endpoint definition config. https://github.com/yandex-cloud/dotnet-sdk/blob/master/tools/GeneratorConfig.cs#L9-L49
