### ISSUE TITLE
service Services_Logging is not supported at this moment

### ISSUE THREAD

**Issue by Krusty84** [yandex-cloud/dotnet-sdk#14]
Hello Dear Yandex Team,

This piece of code:

`var sdk = new Sdk(new OAuthCredentialsProvider("AQA......."));
 Yandex.Cloud.Logging.V1.ReadRequest readRequest = new Yandex.Cloud.Logging.V1.ReadRequest();
 var logresp = sdk.Services.Logging.LogReadingService.ReadAsync(readRequest);`

Generate the following exception:
System.Exception: 'service Services_Logging is not supported at this moment'

Is this my mistake or?

**Comment by nikolaymatrosov** [comment]
I believe that this PR should fix it https://github.com/yandex-cloud/dotnet-sdk/pull/13

**Comment by Krusty84** [comment]
> I believe that this PR should fix it https://github.com/yandex-cloud/dotnet-sdk/pull/13

Dear Nikolay, when can we get the new version sdk with that fix? Thanks

**Comment by DmitryNaumov** [comment]
@Krusty84 should be fixed in 1.2.0, give it a try!
