### ISSUE TITLE
Implement support for ServiceAccount auth

### ISSUE THREAD

**Issue by the-avant-it** [yandex-cloud/dotnet-sdk#29]
Currently you can only use Metadata and OAuth token for auth. Metadata is not applicable for all use cases since it requires your service to run on Yandex Cloud, but OAuth gets expired after one year with is not good also. So service account auth option since it has no expiration problem and not coupled to YC's infrastructure

**Comment by the-avant-it** [comment]
May be, for now, there is way I can request new oauth token to renew it from code automatically?

**Comment by nikolaymatrosov** [comment]
Please avoid using OAuth tokens for any type of automation. Instead, it's recommended to utilize a service account with an authorized key. Here are a few approaches to consider:

1. Implement your own `ICredentialsProvider` to exchange a JWT token, signed by the authorized private key, for access.
2. Use a third-party package that provides this functionality, such as [YandexCloud.IamJwtCredentials](https://www.nuget.org/packages/YandexCloud.IamJwtCredentials).
3. Alternatively, you may wait for the merge of pull request #27, which will add this functionality to the SDK. 

These methods ensure secure and efficient authorization for automated processes.

**Comment by the-avant-it** [comment]
> Use a third-party package that provides this functionality, such as [YandexCloud.IamJwtCredentials](https://www.nuget.org/packages/YandexCloud.IamJwtCredentials).

Looks like what I need, thank you!
